version: '3'

services:
  dbserver:
    build:
      context: ./dockers
      dockerfile: Dockerfile
    container_name: aiv-mongodb-server
    command: bash -ic "cd /app && ls && uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: aiv-mongodb
    ports:
      - 27017:27017
    volumes: 
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    container_name: aiv-mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb