version: '3'

services:
  dbserver:
    build:
      context: .
      dockerfile: dockers/Dockerfile.dev
    container_name: aiv-mongodb-server
    command: bash -ic "cd /app/src && ls && python main.py"
    ports:
      - 8000:8000
    volumes:
      - ./:/app/src
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: aiv-mongodb
    ports:
      - 27017:27017
    volumes: 
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    container_name: aiv-mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb